### ISSUE TITLE
EventBinder fails on KeyDown event in WPF - .NET 5.0

### ISSUE THREAD

**Issue by LarsWork** [Serg046/EventBinder#31]
Hi @Serg046, thanks for a great tool! I run into an Exception when trying to bind to the KeyDown event (and many other events) in my .NET 5 wpf app. See image for the location in the code where it fails in EventBinding.cs (I changed the code slightly for simpler display of nullvalue) :

![image](https://user-images.githubusercontent.com/78616776/114167893-d1f5ed80-992f-11eb-86be-c828e46703c4.png)

The event TextChanged or MouseLeftButtonDown works fine. Here's my xaml:

![image](https://user-images.githubusercontent.com/78616776/114168205-3c0e9280-9930-11eb-960a-fca98ea962dd.png)

Any idea on how to fix, or if I'm doing something wrong?

**Comment by Serg046** [comment]
I'll take a look on this soon. Sorry for the delay, I missed the notification. Btw, I remember some issues with .NET 5. So it is time to fix them.

**Comment by LarsWork** [comment]
That's excellent to hear @Serg046. I'm working with another guy who is trying to make a fix, it might be a good idea if we all share thoughts. He will comment here in a while.

**Comment by Serg046** [comment]
Tbh, I didn't start yet. If you guys can fix it, it will be awesome, we can just merge it and release.

**Comment by LarsWork** [comment]
Thx for your reply! We don't know how to fix it yet, but we've looked at it a bit. The problem is that no attached events are handed, because they cannot be cast to EventInfo. But your readme.md say EventBinder works with "any event". Did attached events work with .NET Framework 4.x?

**Comment by Serg046** [comment]
Default `{Binding}` doesn't understand KeyDown neither. I see a workaround but not sure if it covers all the cases. Anyway, I see another workaround where we put "KeyDown" as a parameter, it will cover everything for sure but then you have to type KeyDown two times which is awful

**Comment by Serg046** [comment]
Released https://www.nuget.org/packages/EventBinder/2.5.0

**Comment by LarsWork** [comment]
Wow, that's fantastic, thank you! I know this is opensource software, so I really didn't expect anything. We'll test it today :-)

**Comment by LarsWork** [comment]
Tested and approved, it works like a charm on KeyDown! Looking forward to see how you actually fixed it in the code, I'm impressed by your skills!
![image](https://user-images.githubusercontent.com/78616776/117252346-1b116280-ae46-11eb-9267-4c1e26f68ff3.png)

**Comment by LarsWork** [comment]
Tested by two separate devs, seems to work very good!

**Comment by Serg046** [comment]
Just for other people who might google this issue, there is another way to bind described [here](https://github.com/Serg046/EventBinder#c-side-binding) - `EventBinding.Bind(uiControl, "SomeEvent", ...)`. This way will find an event using your string provided which is "SomeEvent" for the previous example.
