### ISSUE TITLE
Support for Avalonia v11-preview

### ISSUE THREAD

**Issue by Mrxx99** [Serg046/EventBinder#59]
Hi, it would be nice if you could add support for v11-preview in a preview nuget package, it would only require a version change of Avalonia to a v11-preview. It does need a new build because there is a binary breaking change from pre v11 to v11.

**Comment by Serg046** [comment]
Sorry for the delay, [v2.5.0.2-11.0.0-preview1](https://www.nuget.org/packages/EventBinder.Avalonia/2.5.0.2-11.0.0-preview1) has been released. Please open this once again in case of issues.
