### ISSUE TITLE
[Duplicate #59][Dumb question] How can I use it ?

### ISSUE THREAD

**Issue by Ready4Next** [Serg046/EventBinder#61]
It's said in getting started:

`Just install the nuget package. If it does not work and you get XamlParseException, then apply [assembly: EventBinder.AssemblyReference] attribute in your AssemblyInfo.cs.`

Ok, I have the Exception, and, that's all. How can I add this assembly reference ? Maybe related to #59. If so, I will wait then.

Thanks.

Edited for more Info:

xmlns:e="using:EventBinder" works. But Exception at {e:EventBinding...}
'Could not load file or assembly 'Avalonia.Visuals, Version=0.9.12.0, Culture=neutral, PublicKeyToken=null'. Le fichier spécifié est introuvable.'
So it's a duplicate issue.

**Comment by Serg046** [comment]
What Avolonia version do you use?

**Comment by Ready4Next** [comment]
Hi, thanks for your quick reply ;-)

I'm currently on 11 preview 3, sorry, I forgot to tell.

Thanks for your time :-)

**Comment by Serg046** [comment]
Then yes, looks like the same issue as #59. I will try to fix it soon.

**Comment by Serg046** [comment]
Closed as duplicate. Please note that the assembly name for Avalonia is different (readme is update). So that it should be `xmlns:e="clr-namespace:EventBinder;assembly=EventBinder.Avalonia"` instead of
`xmlns:e="clr-namespace:EventBinder;assembly=EventBinder"`

**Comment by Ready4Next** [comment]
Thanks for the update !
