### ISSUE TITLE
Issue with binding to the same event of different control types (Avalonia)

### ISSUE THREAD

**Issue by stephencanzanese** [Serg046/EventBinder#80]
I'm running into an issue when binding to the same event of different controls. I am binding to the Initialized event of multiple controls. When I do so, I get a System.MissingMethodException 'Constructor on type' with a long hex code. 

<Image Initialized="{e:EventBinding Test}" ... />
<Button Initialized="{e:EventBindingn Test}" .../>

This error is repeated with any Event type that I've tried. (Initialize, AttachedToVisualTree, PointerPressed)

If the controls are all of the same type or if I bind to a different event for each different control, I do not have this issue. It only occurs when binding to the same event of different control types.

**Comment by Serg046** [comment]
Thank you for your contribution. The new version should solve it:
https://www.nuget.org/packages/EventBinder/2.5.3
https://www.nuget.org/packages/EventBinder.Avalonia/2.5.3
https://www.nuget.org/packages/EventBinder.Avalonia/2.5.3-11.0.0-preview1
